### ISSUE TITLE
Load postgresql jdbc driver failed

### ISSUE THREAD

**Issue by mendickxiao** [stevespringett/Alpine#140]
We know the alpine supports the JDK 8 well, how to support the JDK 11? This issue is in JDK 11.

2020-11-30 22:37:11,083 [] INFO [org.eclipse.jetty.util.log] Logging initialized @327ms to org.eclipse.jetty.util.log.Slf4jLog
2020-11-30 22:37:11,244 [] WARN [org.eclipse.jetty.server.Server] ErrorPageMapper not supported for Server level Error Handling
2020-11-30 22:37:11,245 [] INFO [org.eclipse.jetty.server.Server] jetty-9.4.34.v20201102; built: 2020-11-02T14:15:39.302Z; git: e46af88704a893fc12cb0e3bf46e2c7b48a009e7; jvm 1.8.0-262-b10
2020-11-30 22:37:28,691 [] INFO [org.eclipse.jetty.server.session] DefaultSessionIdManager workerName=node0
2020-11-30 22:37:28,691 [] INFO [org.eclipse.jetty.server.session] No SessionScavenger set, using defaults
2020-11-30 22:37:28,693 [] INFO [org.eclipse.jetty.server.session] node0 Scavenging every 660000ms
2020-11-30 22:43:20,787 [] INFO [org.eclipse.jetty.util.log] Logging initialized @317ms to org.eclipse.jetty.util.log.Slf4jLog
2020-11-30 22:43:20,943 [] WARN [org.eclipse.jetty.server.Server] ErrorPageMapper not supported for Server level Error Handling
2020-11-30 22:43:20,945 [] INFO [org.eclipse.jetty.server.Server] jetty-9.4.34.v20201102; built: 2020-11-02T14:15:39.302Z; git: e46af88704a893fc12cb0e3bf46e2c7b48a009e7; jvm 1.8.0-262-b10
2020-11-30 22:43:37,914 [] INFO [org.eclipse.jetty.server.session] DefaultSessionIdManager workerName=node0
2020-11-30 22:43:37,914 [] INFO [org.eclipse.jetty.server.session] No SessionScavenger set, using defaults
2020-11-30 22:43:37,916 [] INFO [org.eclipse.jetty.server.session] node0 Scavenging every 660000ms
2020-11-30 23:24:41,602 [] INFO [org.eclipse.jetty.server.handler.ContextHandler] Started o.e.j.w.WebAppContext@4baf3987{/,file:///C:/Users/mxiao/AppData/Local/Temp/jetty-0_0_0_0-8080-dependency-track-embedded_war-_-any-3787831117176657565/webapp/,AVAILABLE}{file:/C:/Users/mxiao/code/dependency-track/target/dependency-track-embedded.war}
2020-11-30 23:24:41,626 [] INFO [org.eclipse.jetty.server.AbstractConnector] Started ServerConnector@343f4d3d{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
2020-11-30 23:24:41,627 [] INFO [org.eclipse.jetty.server.Server] Started @2481160ms
2020-12-01 00:05:18,635 [] INFO [org.eclipse.jetty.server.AbstractConnector] Stopped ServerConnector@343f4d3d{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
2020-12-01 00:05:18,635 [] INFO [org.eclipse.jetty.server.session] node0 Stopped scavenging
2020-12-01 00:05:18,665 [] INFO [org.eclipse.jetty.server.handler.ContextHandler] Stopped o.e.j.w.WebAppContext@4baf3987{/,file:///C:/Users/mxiao/AppData/Local/Temp/jetty-0_0_0_0-8080-dependency-track-embedded_war-_-any-3787831117176657565/webapp/,STOPPED}{file:/C:/Users/mxiao/code/dependency-track/target/dependency-track-embedded.war}
2020-12-01 00:07:26,922 [] INFO [org.eclipse.jetty.util.log] Logging initialized @425ms to org.eclipse.jetty.util.log.Slf4jLog
2020-12-01 00:07:27,025 [] WARN [org.eclipse.jetty.server.Server] ErrorPageMapper not supported for Server level Error Handling
2020-12-01 00:07:27,026 [] INFO [org.eclipse.jetty.server.Server] jetty-9.4.34.v20201102; built: 2020-11-02T14:15:39.302Z; git: e46af88704a893fc12cb0e3bf46e2c7b48a009e7; jvm 11+28
2020-12-01 00:07:47,168 [] INFO [org.eclipse.jetty.server.session] DefaultSessionIdManager workerName=node0
2020-12-01 00:07:47,169 [] INFO [org.eclipse.jetty.server.session] No SessionScavenger set, using defaults
2020-12-01 00:07:47,170 [] INFO [org.eclipse.jetty.server.session] node0 Scavenging every 600000ms
2020-12-01 00:07:47,189 [] WARN [org.eclipse.jetty.webapp.WebAppContext] Failed startup of context o.e.j.w.WebAppContext@616fe72b{/,file:///C:/Users/mxiao/AppData/Local/Temp/jetty-0_0_0_0-8080-dependency-track-embedded_war-_-any-6145086392483730595/webapp/,UNAVAILABLE}{file:/C:/Users/mxiao/code/dependency-track/target/dependency-track-embedded.war}
java.lang.IllegalArgumentException: object is not an instance of declaring class
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at alpine.Config.expandClasspath(Config.java:510)
	at alpine.Config.expandClasspath(Config.java:492)
	at org.dependencytrack.upgrade.UpgradeInitializer.contextInitialized(UpgradeInitializer.java:56)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:1068)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:572)
	at org.eclipse.jetty.server.handler.ContextHandler.contextInitialized(ContextHandler.java:997)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:746)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:379)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1457)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1422)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:911)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:288)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.server.Server.start(Server.java:423)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.server.Server.doStart(Server.java:387)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at alpine.embedded.EmbeddedJettyServer.main(EmbeddedJettyServer.java:98)
2020-12-01 00:07:47,219 [] INFO [org.eclipse.jetty.server.AbstractConnector] Started ServerConnector@68567e20{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
2020-12-01 00:07:47,220 [] INFO [org.eclipse.jetty.server.Server] Started @20726ms

**Comment by stevespringett** [comment]
Java 11 dropped support for dynamic classpath expansion. Therefore, you cannot use `alpine.database.driver.path` in Java 11. Rather, you have to make sure the database driver is in the classpath when launching Alpine.

**Comment by stevespringett** [comment]
Closing as this is no longer an issue.
