### ISSUE TITLE
Ignore PartialResultException when querying groups via LDAP from Active Directory

### ISSUE THREAD

**Issue by dhelmr** [stevespringett/Alpine#19]
### Issue Type:
  - [ ] defect report
  - [x] enhancement request
  
  
### Current Behavior:
The following error occurs while dependency-track queries the group filters:
```
Error occurred during LDAP synchronizationjavax.naming.PartialResultException: Unprocessed Continuation Reference(s)
    at com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:2917)
    at com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:2891)
    at com.sun.jndi.ldap.AbstractLdapNamingEnumeration.getNextBatch(AbstractLdapNamingEnumeration.java:148)
    at com.sun.jndi.ldap.AbstractLdapNamingEnumeration.hasMoreImpl(AbstractLdapNamingEnumeration.java:217)
    at com.sun.jndi.ldap.AbstractLdapNamingEnumeration.hasMore(AbstractLdapNamingEnumeration.java:189)
    at alpine.auth.LdapConnectionWrapper.getGroups(LdapConnectionWrapper.java:138)
    at alpine.tasks.LdapSyncTask.sync(LdapSyncTask.java:97)
    at alpine.tasks.LdapSyncTask.inform(LdapSyncTask.java:62)
    at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:96)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```
The LDAP server is Active Directory. 

### Steps to Reproduce (if defect):
Related configuration properties:
```
alpine.ldap.enabled=true
alpine.ldap.server.url=ldaps://ad-server.hostname
alpine.ldap.domain=domain.net
alpine.ldap.basedn=DC=domain,DC=private
alpine.ldap.security.auth=simple
alpine.ldap.bind.username=app_dependencytrack@domain.net
alpine.ldap.bind.password=pw
alpine.ldap.auth.username.format=%s@domain.net
alpine.ldap.attribute.name=userPrincipalName
alpine.ldap.attribute.mail=mail
alpine.ldap.groups.filter=(&(objectClass=group)(objectCategory=Group))
alpine.ldap.user.groups.filter=(member:1.2.840.113556.1.4.1941:={USER_DN})
alpine.ldap.user.provisioning=true
alpine.ldap.team.synchronization=true
```
The error occurs, when a user tries to login.
Unfortunately, I cannot share the Active Directory Server configuration. 
I think the error should occur for every Active Directory response that [has a Referral](https://docs.microsoft.com/en-us/windows/desktop/AD/when-referrals-are-generated).

### Expected Behavior:
Add a configuration option to let alpine ignore this Exception.

### Environment:
  
  - Dependency-Track Version: 3.3.1
  - Distribution: [ Docker ]

### Other Details:
According to https://docs.oracle.com/javase/jndi/tutorial/ldap/referral/jndi.html, the value of `Context.REFERRAL` is by default set to IGNORE which means that the LDAP server should not send referrals. However, Active Directory does not support this (see last sentence on the page), and thus the exception is thrown when calling [ne.hasMore](https://github.com/stevespringett/Alpine/blob/master/alpine/src/main/java/alpine/auth/LdapConnectionWrapper.java#L138).

**Comment by stevespringett** [comment]
Targeting Alpine 1.4.3

**Comment by stevespringett** [comment]
I noticed you're using ldaps:// without a port specified. This will default to port 636. Using ports 389 or 636 for Active Directory is not recommended. Rather, port 3268 and 3269 should be used instead.

Have you tried using `ldaps://ad-server.hostname3269`?

**Comment by dhelmr** [comment]
Great, thank you! Using port 3269 also seems to work in our case.
