### ISSUE TITLE
Investigate datanucleus issue where storeMgr is null

### ISSUE THREAD

**Issue by stevespringett** [stevespringett/Alpine#581]
During build, I'm getting a lot of the following exceptions, yet the buiild succeeds.

```
09:52:43.611 [main] ERROR alpine.server.health.checks.DatabaseHealthCheck -- Checking non-transactional connection pool failed
java.lang.NullPointerException: Cannot invoke "org.datanucleus.store.StoreManager.getBooleanProperty(String)" because "this.storeMgr" is null
	at org.datanucleus.store.rdbms.ConnectionFactoryImpl.createManagedConnection(ConnectionFactoryImpl.java:294)
	at org.datanucleus.store.connection.ConnectionManagerImpl.allocateManagedConnection(ConnectionManagerImpl.java:408)
	at org.datanucleus.store.connection.ConnectionManagerImpl.getConnection(ConnectionManagerImpl.java:213)
	at org.datanucleus.store.connection.ConnectionManager.getConnection(ConnectionManager.java:62)
	at org.datanucleus.store.rdbms.query.SQLQuery.performExecute(SQLQuery.java:652)
	at org.datanucleus.store.query.Query.executeQuery(Query.java:2004)
	at org.datanucleus.store.rdbms.query.SQLQuery.executeWithArray(SQLQuery.java:826)
	at org.datanucleus.store.query.Query.execute(Query.java:1875)
	at org.datanucleus.api.jdo.JDOQuery.executeInternal(JDOQuery.java:439)
	at org.datanucleus.api.jdo.JDOQuery.executeResultUnique(JDOQuery.java:393)
	at alpine.server.health.checks.DatabaseHealthCheck.executeQuery(DatabaseHealthCheck.java:94)
	at alpine.server.health.checks.DatabaseHealthCheck.checkNonTransactionalConnectionPool(DatabaseHealthCheck.java:67)
	at alpine.server.health.checks.DatabaseHealthCheck.call(DatabaseHealthCheck.java:48)
	at alpine.server.health.checks.DatabaseHealthCheckTest.testWithSecondaryConnectionFactoryDown(DatabaseHealthCheckTest.java:104)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
09:52:43.611 [main] DEBUG alpine.server.health.checks.DatabaseHealthCheck -- Checking transactional connection pool
```

**Comment by nscuro** [comment]
Will check this. Just verified that it does not happen at runtime, so hopefully just a test that needs tweaking.

**Comment by nscuro** [comment]
I can look into disabling logs for tests if you want @stevespringett.

**Comment by stevespringett** [comment]
> I can look into disabling logs for tests 

No need. Thanks for the investigation. Just wanted to make sure that we didn't introduce behavior that would negatively impact applications built on the framework.
